name: Build and Deploy

on: push

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - uses: taiki-e/install-action@just

      - run: just generate-site
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: site
          publish_dir: ./public
        if: github.ref == 'refs/heads/sources'
