name: Build and Deploy

on: push

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "0.89.4"
          extended: true

      - name: Build
        run: |
          hugo --gc --minify
          cp CNAME public/
          touch public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/sources'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: site
          publish_dir: ./public
